light:
  - platform: mqtt_json
    name: feather_leds
    state_topic: "feather/leds"
    command_topic: "feather/leds/set"
    brightness: true
    rgb: true
    white_value: false
    effect: true
    effect_list:
    - Static
    - Blink
    - Breath
    - Color Wipe
    - Color Wipe Inverse
    - Color Wipe Reverse
    - Color Wipe Reverse Inverse
    - Color Wipe Random
    - Random Color
    - Single Dynamic
    - Multi Dynamic
    - Rainbow
    - Rainbow Cycle
    - Scan
    - Dual Scan
    - Fade
    - Theater Chase
    - Theater Chase Rainbow
    - Running Lights
    - Twinkle
    - Twinkle Random
    - Twinkle Fade
    - Twinkle Fade Random
    - Sparkle
    - Flash Sparkle
    - Hyper Sparkle
    - Strobe
    - Strobe Rainbow
    - Multi Strobe
    - Blink Rainbow
    - Chase White
    - Chase Color
    - Chase Random
    - Chase Rainbow
    - Chase Flash
    - Chase Flash Random
    - Chase Rainbow White
    - Chase Blackout
    - Chase Blackout Rainbow
    - Color Sweep Random
    - Running Color
    - Running Red Blue
    - Running Random
    - Larson Scanner
    - Comet
    - Fireworks
    - Fireworks Random
    - Merry Christmas
    - Fire Flicker
    - Fire Flicker (soft)
    - Fire Flicker (intense)
    - Circus Combustus
    - Halloween
    - Bicolor Chase
    - Tricolor Chase
    - ICU
    optimistic: false
    qos: 0

input_number:
  feather_led_speed:
    name: Speed
    initial: 200
    min: 1
    max: 5000
    step: 100
    unit_of_measurement: "ms"

automation:
  - alias: feather leds animation speed
    id: '1512079408964'
    initial_state: true
    hide_entity: false
    trigger:
    - entity_id: input_number.feather_led_speed
      platform: state
    action:
    - data_template:
        payload_template: '{"speed":{{ trigger.to_state.state | int }}}'
        topic: feather/leds/set
      service: mqtt.publish
  - action:
    - data_template:
        entity_id: input_number.feather_led_speed
        value: '{% if trigger.payload_json.speed %}{{ trigger.payload_json.speed }}{% else %}1{% endif %}'
      service: input_number.set_value
    alias: feather leds animation speed state
    condition: []
    id: '1513300226027'
    trigger:
    - platform: mqtt
      topic: kitchen/leds

group:
  light_feather:
    name: Lights feather
    view: yes
    entities:
    - light.feather_leds
    - input_number.feather_led_speed

